PRINT 'Creating Database';
CREATE DATABASE ProductDB;
GO
PRINT 'Creating Tables'
USE ProductDB;
CREATE TABLE [dbo].[ProductItems]
(
  [Id] uniqueidentifier NOT NULL PRIMARY KEY  DEFAULT (NEWID()),
  [productName] NVARCHAR(100) NOT NULL,
  [department] NVARCHAR(100) NOT NULL,
  [color] NVARCHAR(100) NOT NULL,
  [price] float NOT NULL,
  [productAdjective] NVARCHAR(100) NOT NULL,
  [productMaterial] NVARCHAR(100) NOT NULL,
  [producttype] NVARCHAR(100) NOT NULL,
)
GO
PRINT 'Creating Records'
INSERT INTO [ProductDB].[dbo].[ProductItems]
    ([color], [department], [productName], [price], [productAdjective], [productMaterial], [producttype])
VALUES
('plum', 'Garden', 'Handmade Steel Hat', 434, 'Licensed', 'Concrete', 'Soap'),
('olive', 'Baby', 'Gorgeous Frozen Computer', 767, 'Handcrafted', 'Plastic', 'Keyboard'),
('violet', 'Clothing', 'Generic Cotton Chair', 810, 'Fantastic', 'Steel', 'Bike'),
('green', 'Home', 'Refined Plastic Bacon', 837, 'Licensed', 'Metal', 'Fish'),
('purple', 'Shoes', 'Intelligent Frozen Table', 605, 'Gorgeous', 'Fresh', 'Ball'),
('green', 'Sports', 'Fantastic Frozen Chicken', 586, 'Unbranded', 'Granite', 'Cheese'),
('ivory', 'Toys', 'Awesome Concrete Pants', 6, 'Unbranded', 'Plastic', 'Soap'),
('teal', 'Books', 'Handcrafted Rubber Gloves', 751, 'Awesome', 'Metal', 'Tuna'),
('red', 'Sports', 'Refined Cotton Ball', 348, 'Unbranded', 'Plastic', 'Hat'),
('violet', 'Clothing', 'Practical Concrete Table', 19, 'Practical', 'Wooden', 'Cheese'),
('tan', 'Kids', 'Generic Frozen Sausages', 182, 'Rustic', 'Metal', 'Bacon'),
('salmon', 'Jewelery', 'Generic Metal Tuna', 870, 'Fantastic', 'Steel', 'Shoes'),
('plum', 'Tools', 'Unbranded Plastic Soap', 326, 'Gorgeous', 'Cotton', 'Soap'),
('sky blue', 'Shoes', 'Practical Concrete Fish', 892, 'Handcrafted', 'Plastic', 'Fish'),
('mint green', 'Grocery', 'Ergonomic Plastic Hat', 417, 'Intelligent', 'Cotton', 'Car'),
('blue', 'Beauty', 'Unbranded Granite Table', 713, 'Gorgeous', 'Plastic', 'Sausages'),
('lavender', 'Games', 'Fantastic Wooden Computer', 609, 'Unbranded', 'Cotton', 'Soap'),
('magenta', 'Home', 'Sleek Plastic Pants', 207, 'Rustic', 'Metal', 'Hat'),
('olive', 'Home', 'Unbranded Wooden Bike', 540, 'Practical', 'Granite', 'Pants'),
('indigo', 'Baby', 'Rustic Metal Table', 259, 'Gorgeous', 'Cotton', 'Bike'),
('yellow', 'Jewelery', 'Generic Metal Cheese', 423, 'Practical', 'Steel', 'Salad'),
('sky blue', 'Sports', 'Rustic Granite Towels', 962, 'Handcrafted', 'Fresh', 'Chicken'),
('maroon', 'Jewelery', 'Handcrafted Steel Car', 588, 'Generic', 'Frozen', 'Mouse'),
('mint green', 'Electronics', 'Ergonomic Rubber Table', 315, 'Handmade', 'Fresh', 'Bike'),
('turquoise', 'Computers', 'Refined Frozen Keyboard', 483, 'Practical', 'Metal', 'Mouse'),
('maroon', 'Grocery', 'Intelligent Cotton Fish', 10, 'Practical', 'Wooden', 'Chips'),
('turquoise', 'Sports', 'Small Concrete Shoes', 592, 'Fantastic', 'Frozen', 'Mouse'),
('violet', 'Toys', 'Refined Fresh Table', 629, 'Awesome', 'Wooden', 'Bike'),
('indigo', 'Health', 'Handcrafted Fresh Car', 232, 'Ergonomic', 'Fresh', 'Computer'),
('orange', 'Clothing', 'Sleek Rubber Hat', 533, 'Fantastic', 'Plastic', 'Pants'),
('orchid', 'Industrial', 'Generic Soft Chips', 883, 'Intelligent', 'Metal', 'Salad'),
('purple', 'Health', 'Refined Cotton Mouse', 845, 'Sleek', 'Cotton', 'Cheese'),
('sky blue', 'Sports', 'Handmade Concrete Towels', 175, 'Rustic', 'Wooden', 'Chicken'),
('azure', 'Automotive', 'Handmade Soft Pants', 5, 'Sleek', 'Rubber', 'Shirt'),
('grey', 'Kids', 'Licensed Soft Table', 270, 'Handmade', 'Soft', 'Shirt'),
('azure', 'Kids', 'Sleek Frozen Chair', 620, 'Tasty', 'Fresh', 'Shoes'),
('salmon', 'Beauty', 'Incredible Fresh Towels', 860, 'Unbranded', 'Concrete', 'Bike'),
('blue', 'Movies', 'Generic Wooden Tuna', 191, 'Handcrafted', 'Fresh', 'Chips'),
('tan', 'Garden', 'Small Concrete Chicken', 274, 'Generic', 'Metal', 'Computer'),
('orange', 'Garden', 'Incredible Fresh Bike', 250, 'Licensed', 'Steel', 'Keyboard'),
('green', 'Automotive', 'Intelligent Fresh Car', 25, 'Handcrafted', 'Rubber', 'Soap'),
('salmon', 'Automotive', 'Intelligent Rubber Salad', 268, 'Gorgeous', 'Frozen', 'Hat'),
('green', 'Industrial', 'Small Wooden Cheese', 287, 'Awesome', 'Plastic', 'Computer'),
('olive', 'Computers', 'Unbranded Fresh Bacon', 517, 'Handmade', 'Frozen', 'Cheese'),
('pink', 'Books', 'Incredible Soft Car', 709, 'Unbranded', 'Rubber', 'Shirt'),
('green', 'Movies', 'Intelligent Rubber Cheese', 63, 'Incredible', 'Cotton', 'Towels'),
('salmon', 'Outdoors', 'Generic Metal Bike', 842, 'Ergonomic', 'Rubber', 'Table'),
('lavender', 'Movies', 'Generic Wooden Mouse', 243, 'Incredible', 'Granite', 'Cheese'),
('black', 'Outdoors', 'Practical Soft Pants', 966, 'Small', 'Granite', 'Shirt'),
('mint green', 'Baby', 'Unbranded Wooden Chicken', 76, 'Refined', 'Rubber', 'Salad'),
('cyan', 'Automotive', 'Rustic Cotton Mouse', 981, 'Ergonomic', 'Fresh', 'Salad'),
('plum', 'Home', 'Intelligent Concrete Fish', 453, 'Handmade', 'Steel', 'Sausages'),
('green', 'Beauty', 'Handmade Metal Ball', 937, 'Rustic', 'Concrete', 'Sausages'),
('blue', 'Computers', 'Practical Concrete Bacon', 584, 'Rustic', 'Granite', 'Hat'),
('black', 'Kids', 'Ergonomic Plastic Chips', 634, 'Handcrafted', 'Frozen', 'Chips'),
('cyan', 'Tools', 'Ergonomic Cotton Shirt', 182, 'Refined', 'Steel', 'Chair'),
('turquoise', 'Games', 'Small Plastic Shirt', 174, 'Small', 'Plastic', 'Mouse'),
('maroon', 'Health', 'Sleek Rubber Pants', 956, 'Rustic', 'Granite', 'Table'),
('silver', 'Movies', 'Unbranded Fresh Salad', 735, 'Handcrafted', 'Soft', 'Pants'),
('fuchsia', 'Tools', 'Refined Concrete Salad', 744, 'Sleek', 'Soft', 'Chicken'),
('orange', 'Games', 'Generic Steel Pizza', 821, 'Unbranded', 'Cotton', 'Gloves'),
('cyan', 'Health', 'Unbranded Frozen Tuna', 204, 'Handcrafted', 'Granite', 'Mouse'),
('white', 'Jewelery', 'Fantastic Rubber Chicken', 111, 'Handcrafted', 'Fresh', 'Ball'),
('sky blue', 'Music', 'Awesome Plastic Pants', 582, 'Ergonomic', 'Fresh', 'Tuna'),
('azure', 'Sports', 'Ergonomic Steel Keyboard', 106, 'Licensed', 'Granite', 'Ball'),
('ivory', 'Health', 'Incredible Granite Sausages', 143, 'Refined', 'Metal', 'Bacon'),
('teal', 'Toys', 'Handcrafted Plastic Salad', 414, 'Rustic', 'Plastic', 'Ball'),
('yellow', 'Outdoors', 'Incredible Soft Table', 83, 'Fantastic', 'Concrete', 'Soap'),
('red', 'Electronics', 'Refined Plastic Pizza', 164, 'Gorgeous', 'Wooden', 'Soap'),
('sky blue', 'Games', 'Handmade Frozen Cheese', 889, 'Small', 'Wooden', 'Computer'),
('salmon', 'Books', 'Fantastic Fresh Shoes', 517, 'Awesome', 'Metal', 'Fish'),
('gold', 'Kids', 'Handmade Metal Chair', 562, 'Fantastic', 'Concrete', 'Bacon'),
('purple', 'Tools', 'Awesome Soft Keyboard', 80, 'Incredible', 'Granite', 'Soap'),
('fuchsia', 'Garden', 'Awesome Metal Mouse', 903, 'Ergonomic', 'Granite', 'Chair'),
('white', 'Outdoors', 'Awesome Cotton Towels', 737, 'Generic', 'Wooden', 'Salad'),
('lavender', 'Garden', 'Licensed Frozen Sausages', 2, 'Handmade', 'Plastic', 'Sausages'),
('cyan', 'Shoes', 'Unbranded Concrete Bike', 156, 'Handmade', 'Metal', 'Bike'),
('white', 'Automotive', 'Gorgeous Steel Salad', 388, 'Small', 'Wooden', 'Bike'),
('silver', 'Industrial', 'Handcrafted Rubber Towels', 942, 'Handmade', 'Plastic', 'Bike'),
('plum', 'Tools', 'Awesome Plastic Pizza', 605, 'Unbranded', 'Soft', 'Salad'),
('silver', 'Grocery', 'Gorgeous Soft Sausages', 167, 'Practical', 'Rubber', 'Fish'),
('green', 'Clothing', 'Awesome Cotton Sausages', 690, 'Small', 'Plastic', 'Cheese'),
('orange', 'Outdoors', 'Sleek Steel Sausages', 565, 'Incredible', 'Concrete', 'Ball'),
('magenta', 'Tools', 'Handcrafted Fresh Chicken', 479, 'Sleek', 'Soft', 'Ball'),
('orange', 'Health', 'Sleek Plastic Table', 955, 'Licensed', 'Plastic', 'Car'),
('grey', 'Beauty', 'Ergonomic Granite Pants', 333, 'Handcrafted', 'Cotton', 'Mouse'),
('fuchsia', 'Beauty', 'Refined Frozen Tuna', 86, 'Handmade', 'Soft', 'Gloves'),
('grey', 'Automotive', 'Incredible Fresh Keyboard', 126, 'Unbranded', 'Concrete', 'Gloves'),
('blue', 'Shoes', 'Licensed Steel Computer', 881, 'Practical', 'Wooden', 'Table'),
('plum', 'Toys', 'Sleek Metal Chips', 55, 'Handcrafted', 'Metal', 'Towels'),
('purple', 'Kids', 'Ergonomic Plastic Bacon', 768, 'Gorgeous', 'Granite', 'Computer'),
('teal', 'Sports', 'Small Metal Tuna', 681, 'Unbranded', 'Metal', 'Bacon'),
('blue', 'Electronics', 'Refined Plastic Ball', 988, 'Licensed', 'Steel', 'Soap'),
('maroon', 'Books', 'Generic Steel Keyboard', 66, 'Tasty', 'Granite', 'Bike'),
('blue', 'Sports', 'Awesome Frozen Bike', 542, 'Unbranded', 'Rubber', 'Keyboard'),
('ivory', 'Sports', 'Sleek Concrete Table', 842, 'Tasty', 'Fresh', 'Sausages'),
('purple', 'Tools', 'Rustic Steel Salad', 38, 'Practical', 'Wooden', 'Keyboard'),
('salmon', 'Jewelery', 'Awesome Fresh Ball', 824, 'Unbranded', 'Frozen', 'Salad'),
('teal', 'Baby', 'Unbranded Wooden Shoes', 520, 'Refined', 'Granite', 'Chair'),
('magenta', 'Music', 'Unbranded Steel Chicken', 66, 'Refined', 'Frozen', 'Bike'),
('turquoise', 'Books', 'Gorgeous Plastic Pants', 392, 'Gorgeous', 'Rubber', 'Table'),
('azure', 'Home', 'Rustic Frozen Bike', 75, 'Awesome', 'Soft', 'Bike'),
('mint green', 'Baby', 'Licensed Steel Salad', 914, 'Awesome', 'Rubber', 'Salad'),
('blue', 'Sports', 'Rustic Soft Car', 285, 'Gorgeous', 'Steel', 'Chicken'),
('azure', 'Health', 'Gorgeous Plastic Chips', 448, 'Sleek', 'Steel', 'Shoes'),
('lavender', 'Clothing', 'Unbranded Cotton Pizza', 472, 'Gorgeous', 'Concrete', 'Cheese'),
('orange', 'Computers', 'Small Plastic Cheese', 468, 'Ergonomic', 'Plastic', 'Chair'),
('black', 'Sports', 'Rustic Soft Bike', 72, 'Gorgeous', 'Wooden', 'Tuna'),
('teal', 'Books', 'Rustic Cotton Soap', 198, 'Intelligent', 'Wooden', 'Chips'),
('orchid', 'Grocery', 'Tasty Steel Salad', 397, 'Fantastic', 'Wooden', 'Tuna'),
('mint green', 'Clothing', 'Awesome Metal Tuna', 444, 'Small', 'Cotton', 'Table'),
('orange', 'Toys', 'Awesome Wooden Pizza', 450, 'Small', 'Wooden', 'Pizza'),
('olive', 'Games', 'Sleek Wooden Chicken', 901, 'Small', 'Fresh', 'Car'),
('lime', 'Baby', 'Tasty Soft Pizza', 347, 'Small', 'Granite', 'Car'),
('plum', 'Shoes', 'Handmade Metal Pizza', 876, 'Practical', 'Rubber', 'Salad'),
('blue', 'Electronics', 'Handmade Rubber Chair', 269, 'Fantastic', 'Wooden', 'Salad'),
('blue', 'Garden', 'Ergonomic Fresh Computer', 234, 'Generic', 'Concrete', 'Table'),
('red', 'Industrial', 'Gorgeous Frozen Pants', 500, 'Practical', 'Steel', 'Chicken'),
('red', 'Home', 'Unbranded Fresh Chicken', 456, 'Awesome', 'Plastic', 'Chair'),
('gold', 'Books', 'Sleek Wooden Hat', 3, 'Refined', 'Cotton', 'Car'),
('red', 'Garden', 'Practical Plastic Pizza', 794, 'Awesome', 'Plastic', 'Chair'),
('turquoise', 'Music', 'Generic Cotton Bike', 342, 'Awesome', 'Cotton', 'Sausages'),
('indigo', 'Garden', 'Fantastic Concrete Table', 386, 'Incredible', 'Frozen', 'Shirt'),
('red', 'Kids', 'Unbranded Frozen Pizza', 736, 'Gorgeous', 'Granite', 'Cheese'),
('tan', 'Tools', 'Unbranded Steel Mouse', 275, 'Generic', 'Cotton', 'Chair'),
('purple', 'Electronics', 'Rustic Frozen Chair', 600, 'Awesome', 'Steel', 'Table'),
('salmon', 'Movies', 'Generic Granite Shirt', 769, 'Rustic', 'Granite', 'Chair'),
('mint green', 'Kids', 'Ergonomic Soft Tuna', 256, 'Gorgeous', 'Frozen', 'Cheese'),
('magenta', 'Kids', 'Fantastic Frozen Gloves', 193, 'Tasty', 'Wooden', 'Fish'),
('fuchsia', 'Toys', 'Sleek Plastic Chair', 931, 'Fantastic', 'Steel', 'Mouse'),
('plum', 'Health', 'Handmade Plastic Car', 349, 'Practical', 'Rubber', 'Hat'),
('mint green', 'Music', 'Practical Concrete Bacon', 658, 'Awesome', 'Granite', 'Chicken'),
('cyan', 'Music', 'Incredible Cotton Chair', 114, 'Unbranded', 'Wooden', 'Chips'),
('white', 'Industrial', 'Sleek Granite Pizza', 829, 'Unbranded', 'Cotton', 'Chicken'),
('mint green', 'Movies', 'Incredible Steel Table', 628, 'Practical', 'Soft', 'Chicken'),
('cyan', 'Baby', 'Tasty Rubber Car', 19, 'Licensed', 'Granite', 'Computer'),
('silver', 'Automotive', 'Incredible Soft Pizza', 651, 'Generic', 'Soft', 'Tuna'),
('lavender', 'Jewelery', 'Gorgeous Metal Chips', 702, 'Ergonomic', 'Plastic', 'Computer'),
('black', 'Jewelery', 'Unbranded Plastic Ball', 729, 'Unbranded', 'Plastic', 'Hat'),
('gold', 'Games', 'Rustic Soft Keyboard', 537, 'Ergonomic', 'Rubber', 'Shirt'),
('grey', 'Toys', 'Licensed Soft Towels', 389, 'Awesome', 'Soft', 'Gloves'),
('salmon', 'Games', 'Generic Granite Chair', 914, 'Ergonomic', 'Concrete', 'Soap'),
('magenta', 'Computers', 'Handcrafted Fresh Computer', 19, 'Awesome', 'Frozen', 'Towels'),
('green', 'Shoes', 'Small Metal Bacon', 632, 'Sleek', 'Plastic', 'Chips'),
('plum', 'Jewelery', 'Ergonomic Cotton Tuna', 52, 'Sleek', 'Wooden', 'Pants'),
('yellow', 'Baby', 'Intelligent Frozen Pizza', 623, 'Gorgeous', 'Metal', 'Chicken'),
('orange', 'Grocery', 'Fantastic Wooden Tuna', 93, 'Ergonomic', 'Concrete', 'Bike'),
('teal', 'Clothing', 'Awesome Cotton Sausages', 882, 'Intelligent', 'Plastic', 'Computer'),
('red', 'Health', 'Awesome Steel Sausages', 206, 'Fantastic', 'Cotton', 'Computer'),
('magenta', 'Tools', 'Incredible Wooden Computer', 965, 'Incredible', 'Metal', 'Cheese'),
('salmon', 'Clothing', 'Generic Metal Towels', 155, 'Unbranded', 'Granite', 'Keyboard'),
('gold', 'Garden', 'Sleek Soft Sausages', 168, 'Incredible', 'Wooden', 'Ball'),
('salmon', 'Automotive', 'Intelligent Wooden Table', 347, 'Sleek', 'Metal', 'Mouse'),
('lime', 'Toys', 'Awesome Fresh Chips', 83, 'Rustic', 'Rubber', 'Computer'),
('red', 'Books', 'Incredible Metal Soap', 70, 'Practical', 'Steel', 'Bike'),
('ivory', 'Movies', 'Intelligent Granite Ball', 531, 'Refined', 'Granite', 'Pizza'),
('blue', 'Shoes', 'Incredible Concrete Chips', 954, 'Fantastic', 'Concrete', 'Gloves'),
('lavender', 'Outdoors', 'Licensed Metal Bacon', 585, 'Licensed', 'Granite', 'Soap'),
('indigo', 'Games', 'Unbranded Wooden Sausages', 215, 'Tasty', 'Cotton', 'Fish'),
('olive', 'Sports', 'Handmade Metal Shirt', 808, 'Gorgeous', 'Rubber', 'Mouse'),
('teal', 'Grocery', 'Small Frozen Sausages', 665, 'Refined', 'Concrete', 'Hat'),
('mint green', 'Music', 'Practical Metal Chips', 34, 'Fantastic', 'Steel', 'Chicken'),
('blue', 'Shoes', 'Sleek Soft Chicken', 269, 'Sleek', 'Frozen', 'Table'),
('sky blue', 'Jewelery', 'Licensed Rubber Keyboard', 921, 'Fantastic', 'Fresh', 'Hat'),
('purple', 'Kids', 'Practical Metal Sausages', 606, 'Refined', 'Rubber', 'Shirt'),
('black', 'Baby', 'Handmade Plastic Pants', 942, 'Small', 'Wooden', 'Shirt'),
('maroon', 'Grocery', 'Small Cotton Bacon', 118, 'Handmade', 'Frozen', 'Bike'),
('lavender', 'Home', 'Gorgeous Plastic Salad', 727, 'Refined', 'Cotton', 'Chicken'),
('lime', 'Books', 'Incredible Cotton Soap', 712, 'Handcrafted', 'Metal', 'Chair'),
('teal', 'Computers', 'Ergonomic Fresh Mouse', 504, 'Small', 'Concrete', 'Computer'),
('turquoise', 'Beauty', 'Licensed Concrete Table', 366, 'Unbranded', 'Cotton', 'Computer'),
('orange', 'Beauty', 'Tasty Concrete Bacon', 631, 'Fantastic', 'Concrete', 'Table'),
('indigo', 'Electronics', 'Generic Steel Table', 777, 'Practical', 'Wooden', 'Pizza'),
('lavender', 'Jewelery', 'Awesome Fresh Soap', 586, 'Practical', 'Rubber', 'Gloves'),
('turquoise', 'Kids', 'Intelligent Frozen Bike', 305, 'Unbranded', 'Soft', 'Chicken'),
('violet', 'Baby', 'Awesome Concrete Towels', 652, 'Handcrafted', 'Wooden', 'Bike'),
('mint green', 'Music', 'Practical Plastic Fish', 556, 'Handcrafted', 'Wooden', 'Keyboard'),
('purple', 'Clothing', 'Intelligent Granite Bike', 78, 'Refined', 'Plastic', 'Chips'),
('salmon', 'Kids', 'Refined Rubber Fish', 87, 'Tasty', 'Granite', 'Pizza'),
('red', 'Books', 'Ergonomic Fresh Chips', 704, 'Refined', 'Frozen', 'Shirt'),
('fuchsia', 'Sports', 'Refined Steel Fish', 154, 'Awesome', 'Concrete', 'Table'),
('grey', 'Games', 'Handcrafted Cotton Towels', 704, 'Refined', 'Steel', 'Car'),
('white', 'Health', 'Handcrafted Plastic Chicken', 444, 'Handcrafted', 'Soft', 'Tuna'),
('lime', 'Baby', 'Practical Concrete Shoes', 248, 'Practical', 'Metal', 'Computer'),
('azure', 'Computers', 'Tasty Metal Sausages', 138, 'Handmade', 'Fresh', 'Bike'),
('red', 'Garden', 'Handmade Wooden Salad', 558, 'Awesome', 'Wooden', 'Computer'),
('indigo', 'Automotive', 'Handcrafted Steel Bike', 386, 'Licensed', 'Metal', 'Shoes'),
('fuchsia', 'Games', 'Licensed Wooden Bacon', 995, 'Unbranded', 'Plastic', 'Fish'),
('maroon', 'Sports', 'Ergonomic Steel Fish', 661, 'Intelligent', 'Steel', 'Pants'),
('lime', 'Beauty', 'Practical Granite Fish', 984, 'Rustic', 'Concrete', 'Sausages'),
('pink', 'Games', 'Rustic Frozen Bacon', 741, 'Small', 'Soft', 'Table'),
('pink', 'Kids', 'Practical Granite Bacon', 480, 'Licensed', 'Steel', 'Car'),
('mint green', 'Jewelery', 'Small Concrete Gloves', 649, 'Handcrafted', 'Wooden', 'Shoes'),
('gold', 'Automotive', 'Practical Metal Sausages', 540, 'Fantastic', 'Rubber', 'Fish'),
('olive', 'Tools', 'Awesome Fresh Bike', 772, 'Awesome', 'Fresh', 'Bacon'),
('maroon', 'Outdoors', 'Awesome Plastic Fish', 690, 'Gorgeous', 'Fresh', 'Towels'),
('teal', 'Electronics', 'Handmade Frozen Towels', 851, 'Small', 'Granite', 'Bike'),
('green', 'Outdoors', 'Refined Soft Bike', 60, 'Sleek', 'Plastic', 'Hat'),
('salmon', 'Garden', 'Sleek Fresh Chips', 406, 'Practical', 'Steel', 'Keyboard'),
('red', 'Jewelery', 'Handcrafted Rubber Chicken', 849, 'Licensed', 'Wooden', 'Shoes'),
('orchid', 'Music', 'Rustic Plastic Mouse', 709, 'Small', 'Soft', 'Mouse'),
('fuchsia', 'Tools', 'Licensed Wooden Pizza', 570, 'Fantastic', 'Plastic', 'Car'),
('azure', 'Computers', 'Intelligent Fresh Tuna', 638, 'Licensed', 'Plastic', 'Chair'),
('blue', 'Home', 'Gorgeous Plastic Cheese', 351, 'Handmade', 'Frozen', 'Bike'),
('olive', 'Beauty', 'Awesome Granite Bike', 575, 'Ergonomic', 'Granite', 'Computer'),
('orchid', 'Movies', 'Gorgeous Frozen Salad', 567, 'Handcrafted', 'Soft', 'Car'),
('plum', 'Music', 'Gorgeous Wooden Tuna', 319, 'Small', 'Granite', 'Hat'),
('lime', 'Books', 'Small Granite Table', 679, 'Intelligent', 'Fresh', 'Keyboard'),
('tan', 'Tools', 'Fantastic Wooden Car', 858, 'Fantastic', 'Concrete', 'Salad'),
('green', 'Music', 'Awesome Wooden Gloves', 655, 'Ergonomic', 'Fresh', 'Salad'),
('fuchsia', 'Industrial', 'Fantastic Granite Salad', 31, 'Small', 'Steel', 'Salad'),
('indigo', 'Baby', 'Generic Granite Sausages', 477, 'Gorgeous', 'Granite', 'Towels'),
('silver', 'Industrial', 'Handmade Concrete Soap', 42, 'Licensed', 'Cotton', 'Chips'),
('purple', 'Games', 'Generic Cotton Shirt', 274, 'Incredible', 'Fresh', 'Pants'),
('ivory', 'Health', 'Intelligent Rubber Bike', 892, 'Ergonomic', 'Granite', 'Sausages'),
('grey', 'Books', 'Small Metal Bike', 766, 'Gorgeous', 'Cotton', 'Mouse'),
('magenta', 'Home', 'Practical Soft Soap', 920, 'Incredible', 'Steel', 'Car'),
('azure', 'Home', 'Rustic Rubber Fish', 503, 'Handcrafted', 'Metal', 'Pants'),
('pink', 'Baby', 'Tasty Plastic Soap', 149, 'Small', 'Rubber', 'Shoes'),
('lavender', 'Outdoors', 'Intelligent Metal Ball', 621, 'Refined', 'Cotton', 'Soap'),
('indigo', 'Music', 'Small Rubber Hat', 50, 'Practical', 'Plastic', 'Cheese'),
('yellow', 'Beauty', 'Refined Frozen Ball', 578, 'Ergonomic', 'Plastic', 'Salad'),
('pink', 'Computers', 'Fantastic Soft Chicken', 282, 'Awesome', 'Fresh', 'Gloves'),
('plum', 'Clothing', 'Fantastic Soft Salad', 382, 'Unbranded', 'Concrete', 'Hat'),
('azure', 'Garden', 'Rustic Rubber Salad', 339, 'Sleek', 'Metal', 'Sausages'),
('red', 'Electronics', 'Ergonomic Soft Mouse', 541, 'Handmade', 'Granite', 'Gloves'),
('yellow', 'Garden', 'Unbranded Plastic Mouse', 527, 'Tasty', 'Granite', 'Gloves'),
('fuchsia', 'Garden', 'Handcrafted Frozen Fish', 282, 'Gorgeous', 'Cotton', 'Chair'),
('turquoise', 'Kids', 'Tasty Wooden Car', 602, 'Sleek', 'Fresh', 'Cheese'),
('turquoise', 'Grocery', 'Incredible Granite Tuna', 936, 'Generic', 'Metal', 'Tuna'),
('violet', 'Garden', 'Unbranded Cotton Hat', 257, 'Refined', 'Metal', 'Salad'),
('maroon', 'Books', 'Ergonomic Frozen Soap', 694, 'Handcrafted', 'Concrete', 'Shoes'),
('black', 'Shoes', 'Practical Rubber Ball', 221, 'Licensed', 'Fresh', 'Soap'),
('grey', 'Sports', 'Generic Steel Cheese', 885, 'Generic', 'Metal', 'Tuna'),
('fuchsia', 'Kids', 'Incredible Frozen Soap', 527, 'Rustic', 'Rubber', 'Ball'),
('blue', 'Jewelery', 'Incredible Plastic Fish', 68, 'Awesome', 'Frozen', 'Hat'),
('tan', 'Books', 'Small Fresh Soap', 579, 'Handcrafted', 'Cotton', 'Keyboard'),
('cyan', 'Games', 'Ergonomic Cotton Sausages', 773, 'Refined', 'Soft', 'Gloves'),
('sky blue', 'Clothing', 'Intelligent Plastic Shirt', 467, 'Rustic', 'Fresh', 'Car'),
('blue', 'Garden', 'Handmade Steel Chicken', 990, 'Tasty', 'Concrete', 'Computer'),
('pink', 'Beauty', 'Handmade Concrete Car', 339, 'Handmade', 'Plastic', 'Shirt'),
('magenta', 'Music', 'Fantastic Wooden Gloves', 717, 'Refined', 'Wooden', 'Shirt'),
('lavender', 'Electronics', 'Awesome Soft Tuna', 90, 'Practical', 'Steel', 'Computer'),
('red', 'Health', 'Gorgeous Frozen Chips', 947, 'Licensed', 'Cotton', 'Table'),
('fuchsia', 'Automotive', 'Practical Plastic Cheese', 987, 'Practical', 'Rubber', 'Chair'),
('magenta', 'Electronics', 'Licensed Plastic Mouse', 291, 'Rustic', 'Cotton', 'Towels'),
('lime', 'Beauty', 'Rustic Frozen Shirt', 10, 'Ergonomic', 'Fresh', 'Fish'),
('gold', 'Movies', 'Gorgeous Granite Car', 649, 'Handmade', 'Frozen', 'Computer'),
('orange', 'Movies', 'Small Granite Shirt', 169, 'Tasty', 'Rubber', 'Table'),
('magenta', 'Home', 'Awesome Soft Pants', 297, 'Small', 'Wooden', 'Car'),
('grey', 'Computers', 'Unbranded Plastic Bacon', 392, 'Rustic', 'Frozen', 'Soap'),
('teal', 'Grocery', 'Tasty Concrete Tuna', 495, 'Sleek', 'Steel', 'Computer'),
('orchid', 'Jewelery', 'Awesome Wooden Soap', 380, 'Incredible', 'Concrete', 'Cheese'),
('plum', 'Garden', 'Generic Steel Car', 914, 'Handcrafted', 'Granite', 'Table'),
('orange', 'Sports', 'Sleek Plastic Shoes', 95, 'Practical', 'Rubber', 'Ball'),
('red', 'Baby', 'Intelligent Metal Chicken', 128, 'Unbranded', 'Wooden', 'Tuna'),
('white', 'Beauty', 'Incredible Rubber Chips', 700, 'Licensed', 'Plastic', 'Computer'),
('black', 'Baby', 'Handcrafted Concrete Tuna', 251, 'Intelligent', 'Metal', 'Ball'),
('maroon', 'Outdoors', 'Sleek Plastic Mouse', 977, 'Awesome', 'Wooden', 'Gloves'),
('turquoise', 'Garden', 'Small Metal Soap', 915, 'Generic', 'Rubber', 'Shoes'),
('yellow', 'Games', 'Ergonomic Steel Shoes', 511, 'Rustic', 'Metal', 'Soap'),
('maroon', 'Music', 'Unbranded Steel Fish', 569, 'Generic', 'Fresh', 'Hat'),
('turquoise', 'Toys', 'Incredible Plastic Tuna', 515, 'Unbranded', 'Plastic', 'Pants'),
('fuchsia', 'Toys', 'Refined Concrete Hat', 509, 'Ergonomic', 'Plastic', 'Ball'),
('blue', 'Kids', 'Tasty Plastic Keyboard', 313, 'Tasty', 'Cotton', 'Salad'),
('gold', 'Electronics', 'Tasty Frozen Chicken', 837, 'Small', 'Rubber', 'Sausages'),
('lavender', 'Computers', 'Small Steel Chips', 642, 'Gorgeous', 'Granite', 'Car'),
('plum', 'Automotive', 'Tasty Concrete Pants', 377, 'Unbranded', 'Granite', 'Bacon'),
('plum', 'Grocery', 'Fantastic Soft Computer', 550, 'Gorgeous', 'Concrete', 'Chips'),
('azure', 'Baby', 'Awesome Rubber Salad', 301, 'Small', 'Plastic', 'Chair'),
('white', 'Electronics', 'Rustic Steel Chair', 608, 'Practical', 'Soft', 'Chair'),
('violet', 'Shoes', 'Intelligent Concrete Mouse', 914, 'Unbranded', 'Soft', 'Mouse'),
('tan', 'Music', 'Tasty Steel Fish', 745, 'Handmade', 'Cotton', 'Tuna'),
('ivory', 'Sports', 'Practical Concrete Hat', 635, 'Gorgeous', 'Rubber', 'Soap'),
('green', 'Games', 'Unbranded Plastic Bike', 298, 'Incredible', 'Cotton', 'Hat'),
('pink', 'Baby', 'Awesome Granite Computer', 101, 'Generic', 'Plastic', 'Car'),
('sky blue', 'Shoes', 'Intelligent Wooden Cheese', 472, 'Handcrafted', 'Fresh', 'Table'),
('tan', 'Computers', 'Rustic Plastic Soap', 828, 'Awesome', 'Granite', 'Salad'),
('olive', 'Games', 'Sleek Fresh Soap', 591, 'Rustic', 'Granite', 'Bike'),
('lavender', 'Tools', 'Ergonomic Cotton Computer', 415, 'Rustic', 'Metal', 'Car'),
('pink', 'Automotive', 'Ergonomic Concrete Towels', 862, 'Unbranded', 'Fresh', 'Cheese'),
('red', 'Garden', 'Ergonomic Plastic Hat', 931, 'Fantastic', 'Rubber', 'Car'),
('violet', 'Music', 'Incredible Steel Bacon', 583, 'Incredible', 'Granite', 'Ball'),
('grey', 'Shoes', 'Unbranded Soft Fish', 705, 'Ergonomic', 'Granite', 'Cheese'),
('white', 'Tools', 'Ergonomic Rubber Towels', 736, 'Tasty', 'Rubber', 'Fish'),
('magenta', 'Baby', 'Ergonomic Soft Towels', 628, 'Generic', 'Rubber', 'Towels'),
('sky blue', 'Beauty', 'Ergonomic Rubber Shirt', 722, 'Sleek', 'Wooden', 'Chicken'),
('blue', 'Electronics', 'Handmade Fresh Ball', 458, 'Incredible', 'Frozen', 'Hat'),
('silver', 'Movies', 'Sleek Wooden Hat', 391, 'Sleek', 'Granite', 'Salad'),
('violet', 'Home', 'Refined Granite Shoes', 790, 'Intelligent', 'Frozen', 'Shirt'),
('orange', 'Baby', 'Licensed Plastic Bacon', 322, 'Intelligent', 'Cotton', 'Chicken'),
('yellow', 'Toys', 'Tasty Fresh Sausages', 703, 'Ergonomic', 'Rubber', 'Table'),
('silver', 'Shoes', 'Small Concrete Sausages', 189, 'Ergonomic', 'Concrete', 'Sausages'),
('sky blue', 'Tools', 'Unbranded Frozen Sausages', 511, 'Fantastic', 'Steel', 'Chair'),
('maroon', 'Music', 'Handmade Granite Mouse', 158, 'Practical', 'Granite', 'Shoes'),
('sky blue', 'Music', 'Awesome Cotton Soap', 816, 'Handcrafted', 'Granite', 'Chicken'),
('red', 'Sports', 'Incredible Fresh Towels', 237, 'Intelligent', 'Metal', 'Pants'),
('pink', 'Health', 'Tasty Cotton Chair', 912, 'Gorgeous', 'Cotton', 'Shirt'),
('orange', 'Sports', 'Awesome Granite Pizza', 50, 'Ergonomic', 'Metal', 'Soap'),
('black', 'Garden', 'Intelligent Granite Pants', 842, 'Handmade', 'Fresh', 'Salad'),
('plum', 'Music', 'Practical Rubber Chicken', 951, 'Generic', 'Granite', 'Pizza'),
('teal', 'Kids', 'Gorgeous Granite Keyboard', 602, 'Handmade', 'Frozen', 'Mouse'),
('mint green', 'Grocery', 'Unbranded Plastic Ball', 26, 'Rustic', 'Cotton', 'Keyboard'),
('magenta', 'Clothing', 'Unbranded Frozen Bacon', 657, 'Awesome', 'Plastic', 'Pizza'),
('fuchsia', 'Sports', 'Intelligent Metal Chips', 356, 'Handmade', 'Frozen', 'Pants'),
('ivory', 'Industrial', 'Awesome Cotton Ball', 393, 'Tasty', 'Fresh', 'Chicken'),
('sky blue', 'Toys', 'Practical Plastic Ball', 622, 'Handmade', 'Soft', 'Tuna'),
('orchid', 'Toys', 'Ergonomic Steel Tuna', 832, 'Small', 'Granite', 'Sausages'),
('olive', 'Toys', 'Intelligent Concrete Tuna', 869, 'Refined', 'Cotton', 'Pants'),
('magenta', 'Baby', 'Refined Concrete Hat', 830, 'Small', 'Wooden', 'Tuna'),
('tan', 'Baby', 'Awesome Concrete Hat', 311, 'Refined', 'Cotton', 'Car'),
('turquoise', 'Sports', 'Incredible Rubber Shirt', 564, 'Fantastic', 'Metal', 'Shirt'),
('azure', 'Outdoors', 'Awesome Cotton Bike', 148, 'Small', 'Concrete', 'Mouse'),
('blue', 'Tools', 'Gorgeous Cotton Shirt', 775, 'Refined', 'Granite', 'Mouse'),
('plum', 'Books', 'Ergonomic Concrete Car', 537, 'Refined', 'Plastic', 'Car'),
('white', 'Automotive', 'Awesome Steel Pizza', 291, 'Handcrafted', 'Metal', 'Salad'),
('lavender', 'Shoes', 'Ergonomic Wooden Shirt', 355, 'Tasty', 'Frozen', 'Sausages'),
('purple', 'Kids', 'Sleek Granite Cheese', 444, 'Licensed', 'Fresh', 'Fish'),
('teal', 'Home', 'Intelligent Granite Sausages', 323, 'Ergonomic', 'Concrete', 'Chips'),
('silver', 'Jewelery', 'Generic Rubber Car', 54, 'Tasty', 'Wooden', 'Car'),
('ivory', 'Shoes', 'Gorgeous Soft Ball', 692, 'Licensed', 'Soft', 'Computer'),
('black', 'Sports', 'Gorgeous Wooden Keyboard', 508, 'Unbranded', 'Granite', 'Sausages'),
('olive', 'Movies', 'Licensed Frozen Towels', 626, 'Sleek', 'Rubber', 'Chicken'),
('indigo', 'Toys', 'Rustic Frozen Hat', 320, 'Small', 'Fresh', 'Soap'),
('maroon', 'Computers', 'Rustic Frozen Cheese', 372, 'Refined', 'Plastic', 'Salad'),
('azure', 'Music', 'Tasty Rubber Towels', 372, 'Generic', 'Metal', 'Hat'),
('red', 'Games', 'Unbranded Metal Soap', 916, 'Generic', 'Metal', 'Sausages'),
('cyan', 'Automotive', 'Intelligent Steel Shoes', 673, 'Small', 'Plastic', 'Computer'),
('grey', 'Sports', 'Generic Frozen Bike', 900, 'Intelligent', 'Wooden', 'Keyboard'),
('salmon', 'Computers', 'Rustic Metal Salad', 253, 'Small', 'Frozen', 'Shirt'),
('black', 'Music', 'Intelligent Metal Sausages', 824, 'Tasty', 'Soft', 'Computer'),
('azure', 'Grocery', 'Handcrafted Metal Bike', 47, 'Fantastic', 'Soft', 'Cheese'),
('black', 'Electronics', 'Intelligent Rubber Chicken', 562, 'Incredible', 'Steel', 'Pizza'),
('mint green', 'Movies', 'Intelligent Wooden Gloves', 302, 'Tasty', 'Plastic', 'Bike'),
('maroon', 'Grocery', 'Ergonomic Metal Table', 382, 'Small', 'Soft', 'Bike'),
('purple', 'Computers', 'Gorgeous Metal Chair', 324, 'Handcrafted', 'Granite', 'Towels'),
('maroon', 'Kids', 'Ergonomic Steel Chips', 165, 'Intelligent', 'Soft', 'Tuna'),
('cyan', 'Industrial', 'Unbranded Rubber Chair', 361, 'Ergonomic', 'Rubber', 'Table'),
('lavender', 'Tools', 'Intelligent Soft Shoes', 937, 'Ergonomic', 'Soft', 'Bike'),
('fuchsia', 'Health', 'Licensed Fresh Mouse', 221, 'Tasty', 'Soft', 'Ball'),
('lavender', 'Computers', 'Licensed Cotton Shirt', 831, 'Handmade', 'Steel', 'Ball'),
('yellow', 'Jewelery', 'Generic Frozen Towels', 660, 'Small', 'Wooden', 'Chicken'),
('yellow', 'Baby', 'Incredible Plastic Cheese', 435, 'Sleek', 'Concrete', 'Bacon'),
('orange', 'Movies', 'Refined Steel Bike', 529, 'Unbranded', 'Soft', 'Table'),
('ivory', 'Automotive', 'Awesome Wooden Shirt', 430, 'Practical', 'Fresh', 'Soap'),
('teal', 'Music', 'Awesome Concrete Shirt', 55, 'Rustic', 'Concrete', 'Car'),
('plum', 'Games', 'Small Cotton Bike', 614, 'Small', 'Plastic', 'Keyboard'),
('silver', 'Grocery', 'Ergonomic Wooden Chicken', 957, 'Practical', 'Frozen', 'Shirt'),
('green', 'Garden', 'Gorgeous Cotton Sausages', 261, 'Handmade', 'Soft', 'Fish'),
('purple', 'Grocery', 'Intelligent Wooden Tuna', 741, 'Gorgeous', 'Cotton', 'Shoes'),
('white', 'Electronics', 'Tasty Rubber Table', 264, 'Small', 'Concrete', 'Bacon'),
('sky blue', 'Outdoors', 'Generic Wooden Salad', 483, 'Incredible', 'Granite', 'Salad'),
('orange', 'Tools', 'Gorgeous Metal Car', 954, 'Practical', 'Steel', 'Salad'),
('azure', 'Garden', 'Licensed Soft Chips', 889, 'Sleek', 'Fresh', 'Computer'),
('orchid', 'Toys', 'Small Soft Shirt', 335, 'Licensed', 'Soft', 'Hat'),
('magenta', 'Tools', 'Sleek Cotton Bacon', 530, 'Handcrafted', 'Metal', 'Table'),
('mint green', 'Movies', 'Gorgeous Fresh Chips', 280, 'Refined', 'Plastic', 'Fish'),
('grey', 'Kids', 'Small Cotton Salad', 875, 'Tasty', 'Granite', 'Chips'),
('cyan', 'Garden', 'Handmade Wooden Chicken', 147, 'Unbranded', 'Fresh', 'Table'),
('green', 'Baby', 'Handmade Frozen Pants', 954, 'Small', 'Frozen', 'Sausages'),
('salmon', 'Sports', 'Awesome Frozen Hat', 983, 'Practical', 'Concrete', 'Shirt'),
('cyan', 'Health', 'Rustic Granite Hat', 283, 'Gorgeous', 'Frozen', 'Shoes'),
('olive', 'Baby', 'Gorgeous Steel Table', 27, 'Refined', 'Cotton', 'Bike'),
('purple', 'Tools', 'Gorgeous Fresh Chair', 183, 'Small', 'Wooden', 'Keyboard'),
('teal', 'Jewelery', 'Sleek Rubber Mouse', 746, 'Licensed', 'Rubber', 'Fish'),
('lavender', 'Computers', 'Incredible Soft Tuna', 386, 'Rustic', 'Concrete', 'Shirt'),
('maroon', 'Health', 'Unbranded Soft Chips', 944, 'Small', 'Soft', 'Keyboard'),
('orchid', 'Movies', 'Practical Soft Table', 128, 'Handcrafted', 'Concrete', 'Towels'),
('tan', 'Kids', 'Handcrafted Steel Soap', 316, 'Tasty', 'Plastic', 'Shirt'),
('grey', 'Toys', 'Refined Concrete Sausages', 919, 'Practical', 'Soft', 'Shoes'),
('red', 'Tools', 'Incredible Plastic Hat', 755, 'Gorgeous', 'Fresh', 'Gloves'),
('mint green', 'Garden', 'Fantastic Metal Cheese', 100, 'Intelligent', 'Granite', 'Chair'),
('pink', 'Electronics', 'Generic Plastic Bacon', 28, 'Refined', 'Fresh', 'Gloves'),
('red', 'Toys', 'Fantastic Granite Bike', 954, 'Practical', 'Steel', 'Mouse'),
('magenta', 'Health', 'Handcrafted Steel Chicken', 171, 'Licensed', 'Fresh', 'Salad'),
('orchid', 'Computers', 'Awesome Soft Table', 257, 'Incredible', 'Rubber', 'Pizza'),
('indigo', 'Sports', 'Handcrafted Frozen Chips', 784, 'Tasty', 'Rubber', 'Mouse'),
('silver', 'Games', 'Fantastic Metal Chair', 79, 'Small', 'Frozen', 'Ball'),
('purple', 'Electronics', 'Ergonomic Frozen Mouse', 326, 'Generic', 'Soft', 'Keyboard'),
('teal', 'Electronics', 'Handmade Concrete Mouse', 924, 'Sleek', 'Granite', 'Pizza'),
('yellow', 'Jewelery', 'Generic Steel Gloves', 398, 'Unbranded', 'Cotton', 'Computer'),
('lime', 'Books', 'Refined Soft Keyboard', 0, 'Refined', 'Frozen', 'Table'),
('teal', 'Shoes', 'Unbranded Rubber Bacon', 545, 'Generic', 'Metal', 'Pants'),
('lavender', 'Sports', 'Awesome Rubber Shoes', 798, 'Licensed', 'Fresh', 'Pizza'),
('orange', 'Baby', 'Rustic Steel Keyboard', 951, 'Incredible', 'Plastic', 'Pizza'),
('olive', 'Outdoors', 'Tasty Metal Chips', 766, 'Rustic', 'Wooden', 'Pizza'),
('green', 'Electronics', 'Ergonomic Rubber Sausages', 709, 'Small', 'Plastic', 'Fish'),
('teal', 'Movies', 'Awesome Metal Soap', 814, 'Fantastic', 'Rubber', 'Chips'),
('magenta', 'Shoes', 'Rustic Steel Chips', 213, 'Practical', 'Steel', 'Bike'),
('fuchsia', 'Books', 'Rustic Rubber Pants', 142, 'Practical', 'Rubber', 'Bike'),
('blue', 'Home', 'Handcrafted Concrete Shoes', 89, 'Sleek', 'Concrete', 'Keyboard'),
('yellow', 'Tools', 'Unbranded Rubber Soap', 441, 'Tasty', 'Rubber', 'Gloves'),
('black', 'Computers', 'Handcrafted Steel Soap', 240, 'Ergonomic', 'Cotton', 'Towels'),
('fuchsia', 'Books', 'Licensed Cotton Bacon', 681, 'Awesome', 'Cotton', 'Car'),
('purple', 'Grocery', 'Generic Concrete Chicken', 485, 'Handmade', 'Wooden', 'Towels'),
('purple', 'Jewelery', 'Gorgeous Concrete Keyboard', 370, 'Practical', 'Plastic', 'Keyboard'),
('red', 'Baby', 'Ergonomic Cotton Tuna', 566, 'Fantastic', 'Granite', 'Table'),
('grey', 'Industrial', 'Incredible Concrete Tuna', 915, 'Practical', 'Rubber', 'Bike'),
('lime', 'Games', 'Handcrafted Soft Towels', 853, 'Practical', 'Cotton', 'Pants'),
('orchid', 'Computers', 'Rustic Soft Tuna', 30, 'Unbranded', 'Soft', 'Chicken'),
('green', 'Sports', 'Incredible Fresh Fish', 25, 'Small', 'Soft', 'Chips'),
('teal', 'Home', 'Awesome Steel Car', 25, 'Licensed', 'Wooden', 'Computer'),
('plum', 'Sports', 'Gorgeous Soft Shirt', 664, 'Gorgeous', 'Steel', 'Mouse'),
('white', 'Music', 'Incredible Frozen Chips', 781, 'Awesome', 'Concrete', 'Shoes'),
('orchid', 'Games', 'Intelligent Metal Pizza', 331, 'Handmade', 'Soft', 'Tuna'),
('tan', 'Toys', 'Sleek Frozen Cheese', 383, 'Practical', 'Granite', 'Gloves'),
('olive', 'Home', 'Ergonomic Wooden Chair', 65, 'Practical', 'Granite', 'Car'),
('magenta', 'Tools', 'Small Wooden Chips', 595, 'Small', 'Cotton', 'Soap'),
('violet', 'Grocery', 'Intelligent Wooden Towels', 822, 'Incredible', 'Granite', 'Sausages'),
('ivory', 'Health', 'Unbranded Frozen Shoes', 820, 'Generic', 'Frozen', 'Sausages'),
('yellow', 'Computers', 'Licensed Wooden Pizza', 420, 'Awesome', 'Plastic', 'Bacon'),
('orchid', 'Grocery', 'Small Plastic Bacon', 636, 'Incredible', 'Fresh', 'Bike'),
('gold', 'Beauty', 'Small Wooden Chicken', 900, 'Sleek', 'Soft', 'Chips'),
('black', 'Jewelery', 'Handmade Soft Keyboard', 564, 'Handmade', 'Granite', 'Tuna'),
('maroon', 'Baby', 'Rustic Steel Keyboard', 400, 'Licensed', 'Concrete', 'Bike'),
('yellow', 'Industrial', 'Tasty Wooden Towels', 76, 'Refined', 'Plastic', 'Chicken'),
('tan', 'Books', 'Handmade Plastic Sausages', 481, 'Generic', 'Granite', 'Table'),
('white', 'Music', 'Small Metal Chips', 667, 'Refined', 'Cotton', 'Computer'),
('magenta', 'Kids', 'Generic Rubber Hat', 185, 'Handcrafted', 'Frozen', 'Tuna'),
('azure', 'Baby', 'Ergonomic Wooden Tuna', 233, 'Sleek', 'Granite', 'Computer'),
('turquoise', 'Toys', 'Rustic Concrete Ball', 143, 'Sleek', 'Cotton', 'Shirt'),
('azure', 'Computers', 'Intelligent Wooden Hat', 779, 'Sleek', 'Wooden', 'Computer'),
('orange', 'Shoes', 'Incredible Fresh Chips', 200, 'Awesome', 'Frozen', 'Fish'),
('orange', 'Games', 'Generic Granite Chips', 369, 'Handcrafted', 'Plastic', 'Ball'),
('azure', 'Movies', 'Practical Plastic Chicken', 385, 'Generic', 'Soft', 'Pizza'),
('maroon', 'Outdoors', 'Handmade Fresh Hat', 621, 'Sleek', 'Rubber', 'Chips'),
('lime', 'Garden', 'Rustic Frozen Hat', 287, 'Practical', 'Rubber', 'Shirt'),
('lavender', 'Tools', 'Licensed Rubber Bike', 21, 'Fantastic', 'Frozen', 'Salad'),
('salmon', 'Books', 'Handcrafted Frozen Bacon', 29, 'Unbranded', 'Fresh', 'Soap'),
('orchid', 'Sports', 'Licensed Metal Car', 597, 'Small', 'Fresh', 'Pizza'),
('teal', 'Sports', 'Gorgeous Wooden Ball', 598, 'Handcrafted', 'Rubber', 'Salad'),
('indigo', 'Computers', 'Practical Fresh Computer', 612, 'Practical', 'Soft', 'Hat'),
('pink', 'Movies', 'Practical Plastic Keyboard', 633, 'Ergonomic', 'Rubber', 'Fish'),
('sky blue', 'Games', 'Sleek Steel Table', 656, 'Refined', 'Metal', 'Ball'),
('teal', 'Industrial', 'Awesome Metal Chair', 589, 'Generic', 'Cotton', 'Salad'),
('orange', 'Tools', 'Tasty Frozen Pizza', 954, 'Rustic', 'Steel', 'Ball'),
('orange', 'Games', 'Generic Rubber Cheese', 191, 'Ergonomic', 'Soft', 'Soap'),
('olive', 'Baby', 'Handmade Frozen Chair', 258, 'Refined', 'Metal', 'Sausages'),
('mint green', 'Automotive', 'Practical Plastic Pizza', 453, 'Practical', 'Concrete', 'Fish'),
('teal', 'Health', 'Fantastic Frozen Tuna', 590, 'Generic', 'Metal', 'Chair'),
('teal', 'Tools', 'Gorgeous Plastic Salad', 58, 'Practical', 'Granite', 'Shoes'),
('teal', 'Shoes', 'Intelligent Concrete Tuna', 500, 'Small', 'Frozen', 'Ball'),
('gold', 'Grocery', 'Gorgeous Metal Pants', 278, 'Refined', 'Wooden', 'Car'),
('maroon', 'Outdoors', 'Intelligent Plastic Ball', 718, 'Rustic', 'Steel', 'Car'),
('turquoise', 'Jewelery', 'Sleek Soft Chips', 924, 'Generic', 'Cotton', 'Computer'),
('orchid', 'Automotive', 'Tasty Rubber Chair', 760, 'Unbranded', 'Frozen', 'Car'),
('lime', 'Music', 'Generic Fresh Soap', 509, 'Handcrafted', 'Cotton', 'Bike'),
('ivory', 'Beauty', 'Handcrafted Cotton Table', 647, 'Generic', 'Granite', 'Shoes'),
('yellow', 'Industrial', 'Incredible Rubber Cheese', 933, 'Small', 'Steel', 'Chair'),
('plum', 'Tools', 'Incredible Fresh Towels', 593, 'Refined', 'Fresh', 'Chicken'),
('pink', 'Health', 'Generic Concrete Ball', 14, 'Intelligent', 'Granite', 'Bike'),
('orange', 'Music', 'Sleek Fresh Towels', 805, 'Ergonomic', 'Wooden', 'Car'),
('turquoise', 'Sports', 'Awesome Soft Chips', 1, 'Practical', 'Steel', 'Chips'),
('lavender', 'Games', 'Rustic Granite Bacon', 274, 'Unbranded', 'Wooden', 'Gloves'),
('blue', 'Shoes', 'Licensed Wooden Bacon', 895, 'Awesome', 'Cotton', 'Chair'),
('turquoise', 'Kids', 'Sleek Plastic Ball', 600, 'Gorgeous', 'Plastic', 'Table'),
('violet', 'Automotive', 'Sleek Metal Chair', 451, 'Rustic', 'Concrete', 'Fish'),
('maroon', 'Music', 'Unbranded Frozen Cheese', 43, 'Tasty', 'Wooden', 'Bacon'),
('tan', 'Outdoors', 'Gorgeous Rubber Hat', 57, 'Ergonomic', 'Plastic', 'Chicken'),
('azure', 'Electronics', 'Awesome Granite Salad', 653, 'Ergonomic', 'Plastic', 'Sausages'),
('mint green', 'Tools', 'Practical Frozen Pants', 929, 'Generic', 'Cotton', 'Bike'),
('turquoise', 'Electronics', 'Gorgeous Rubber Bike', 562, 'Awesome', 'Fresh', 'Cheese'),
('violet', 'Toys', 'Awesome Metal Chair', 671, 'Tasty', 'Soft', 'Keyboard'),
('lime', 'Automotive', 'Incredible Frozen Table', 40, 'Gorgeous', 'Plastic', 'Chair'),
('salmon', 'Baby', 'Awesome Plastic Salad', 402, 'Gorgeous', 'Concrete', 'Gloves'),
('magenta', 'Books', 'Refined Metal Gloves', 193, 'Small', 'Fresh', 'Salad'),
('teal', 'Movies', 'Unbranded Soft Chair', 734, 'Unbranded', 'Plastic', 'Gloves'),
('turquoise', 'Jewelery', 'Small Cotton Computer', 846, 'Unbranded', 'Soft', 'Computer'),
('azure', 'Games', 'Ergonomic Soft Chair', 313, 'Small', 'Metal', 'Towels'),
('green', 'Home', 'Rustic Wooden Salad', 219, 'Practical', 'Wooden', 'Salad'),
('tan', 'Health', 'Tasty Frozen Pants', 340, 'Incredible', 'Wooden', 'Ball'),
('grey', 'Games', 'Handcrafted Frozen Salad', 297, 'Tasty', 'Metal', 'Keyboard'),
('orchid', 'Beauty', 'Awesome Frozen Keyboard', 397, 'Sleek', 'Concrete', 'Mouse'),
('plum', 'Movies', 'Generic Cotton Fish', 888, 'Rustic', 'Granite', 'Soap'),
('salmon', 'Tools', 'Tasty Frozen Gloves', 547, 'Practical', 'Frozen', 'Car'),
('plum', 'Books', 'Handcrafted Cotton Ball', 718, 'Gorgeous', 'Steel', 'Sausages'),
('azure', 'Jewelery', 'Unbranded Cotton Salad', 257, 'Licensed', 'Soft', 'Shoes'),
('white', 'Health', 'Intelligent Granite Cheese', 821, 'Awesome', 'Cotton', 'Sausages'),
('olive', 'Movies', 'Sleek Fresh Chips', 448, 'Practical', 'Wooden', 'Pizza'),
('magenta', 'Garden', 'Practical Fresh Shirt', 219, 'Handcrafted', 'Steel', 'Salad'),
('indigo', 'Sports', 'Generic Plastic Pants', 436, 'Handmade', 'Rubber', 'Tuna'),
('gold', 'Movies', 'Sleek Frozen Fish', 475, 'Incredible', 'Steel', 'Ball'),
('fuchsia', 'Sports', 'Sleek Soft Soap', 526, 'Licensed', 'Granite', 'Tuna'),
('lime', 'Sports', 'Generic Frozen Ball', 42, 'Small', 'Cotton', 'Soap'),
('azure', 'Shoes', 'Sleek Wooden Soap', 330, 'Gorgeous', 'Granite', 'Salad'),
('ivory', 'Automotive', 'Small Steel Towels', 636, 'Awesome', 'Concrete', 'Gloves'),
('sky blue', 'Jewelery', 'Small Plastic Chips', 591, 'Intelligent', 'Cotton', 'Fish'),
('pink', 'Beauty', 'Handcrafted Rubber Chair', 110, 'Refined', 'Plastic', 'Ball'),
('violet', 'Baby', 'Intelligent Soft Computer', 34, 'Small', 'Concrete', 'Gloves'),
('fuchsia', 'Jewelery', 'Handcrafted Metal Fish', 656, 'Intelligent', 'Granite', 'Pizza'),
('black', 'Garden', 'Ergonomic Wooden Cheese', 659, 'Licensed', 'Cotton', 'Towels'),
('cyan', 'Beauty', 'Sleek Frozen Sausages', 704, 'Handmade', 'Cotton', 'Bike'),
('sky blue', 'Industrial', 'Small Wooden Pants', 835, 'Rustic', 'Fresh', 'Towels'),
('fuchsia', 'Health', 'Gorgeous Steel Chair', 599, 'Small', 'Granite', 'Ball'),
('magenta', 'Clothing', 'Handmade Wooden Pants', 233, 'Gorgeous', 'Frozen', 'Chair'),
('sky blue', 'Outdoors', 'Ergonomic Cotton Chicken', 202, 'Practical', 'Concrete', 'Car'),
('salmon', 'Toys', 'Small Soft Chair', 979, 'Tasty', 'Plastic', 'Cheese'),
('yellow', 'Tools', 'Ergonomic Granite Salad', 931, 'Fantastic', 'Rubber', 'Chicken'),
('maroon', 'Shoes', 'Intelligent Cotton Sausages', 695, 'Small', 'Steel', 'Cheese'),
('yellow', 'Computers', 'Unbranded Concrete Ball', 486, 'Sleek', 'Soft', 'Shoes');

GO